
package com.oil.detection.sms;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import javax.xml.namespace.QName;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2015-12-29T21:34:53.562+08:00
 * Generated source version: 3.1.4
 * 
 */
public final class WebService1Soap_WebService1Soap12_Client {

    private static final QName SERVICE_NAME = new QName("http://tempuri.org/", "WebService1");

    private WebService1Soap_WebService1Soap12_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = WebService1.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        WebService1 ss = new WebService1(wsdlURL, SERVICE_NAME);
        WebService1Soap port = ss.getWebService1Soap12();  
        
        {
        System.out.println("Invoking smsSend...");
        java.lang.String _smsSend_ps = "jkx12345678";
        java.lang.String _smsSend_tel = "13436458697";
        java.lang.String _smsSend_c = "aaaa";
        java.lang.String _smsSend__return = port.smsSend(_smsSend_ps, _smsSend_tel, _smsSend_c);
        System.out.println("smsSend.result=" + _smsSend__return);


        }

        System.exit(0);
    }

}
