
package com.oil.detection.sms;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import javax.xml.namespace.QName;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2015-12-29T21:34:53.622+08:00
 * Generated source version: 3.1.4
 * 
 */
public final class WebService1Soap_WebService1Soap_Client {

    private static final QName SERVICE_NAME = new QName("http://tempuri.org/", "WebService1");

    private WebService1Soap_WebService1Soap_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = WebService1.WSDL_LOCATION;

        WebService1 ss = new WebService1(wsdlURL, SERVICE_NAME);
        WebService1Soap port = ss.getWebService1Soap();  
        
        {
        System.out.println("Invoking smsSend...");
        java.lang.String _smsSend_ps = "jkx12345678";
        java.lang.String _smsSend_tel = "13436458697";
        java.lang.String _smsSend_c = "ddd";
        java.lang.String _smsSend__return = port.smsSend(_smsSend_ps, _smsSend_tel, _smsSend_c);
        System.out.println("smsSend.result=" + _smsSend__return);

        }

        System.exit(0);
    }

}
