package com.oil.detection.sms;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2015-12-29T21:34:53.632+08:00
 * Generated source version: 3.1.4
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "WebService1Soap")
@XmlSeeAlso({ObjectFactory.class})
public interface WebService1Soap {

    @WebMethod(operationName = "sms_send", action = "http://tempuri.org/sms_send")
    @RequestWrapper(localName = "sms_send", targetNamespace = "http://tempuri.org/", className = "com.oil.detection.sms.SmsSend")
    @ResponseWrapper(localName = "sms_sendResponse", targetNamespace = "http://tempuri.org/", className = "com.oil.detection.sms.SmsSendResponse")
    @WebResult(name = "sms_sendResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String smsSend(
        @WebParam(name = "ps", targetNamespace = "http://tempuri.org/")
        java.lang.String ps,
        @WebParam(name = "tel", targetNamespace = "http://tempuri.org/")
        java.lang.String tel,
        @WebParam(name = "c", targetNamespace = "http://tempuri.org/")
        java.lang.String c
    );
}
